apiVersion: v1
kind: Pod
metadata:
  name: kong-oidc-tool
  namespace: kong
spec:
  containers:
  - name: alpine
    image:  643vlk6z.gra7.container-registry.ovh.net/world-cereal/kong-oidc-tool:1.0
    command: ["bin/sh", "-c"]
    args: ["sleep infinity"]
  restartPolicy: OnFailure
  imagePullSecrets:
        - name: harborcs

