# Default values for regards-common.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  registry: 643vlk6z.gra7.container-registry.ovh.net/world-cereal
  name: mapproxy
  tag: latest
  #pullPolicy: IfNotPresent

imagePullSecrets:
  - name: harborcs

# fixes Multi-Attach error for volume
deploymentStrategy:
  type: Recreate

nodeSelector:
    role: kong

# livenessProbe:
#   httpGet:
#     path: /
#     port: http
#   initialDelaySeconds: 20
#   timeoutSeconds: 10
#   periodSeconds: 5

# readinessProbe:
#   httpGet:
#     path: /
#     port: http
#   initialDelaySeconds: 5
#   timeoutSeconds: 2
#   periodSeconds: 5

persistence:
  accessMode: ReadWriteOnce
  volumeMode: Filesystem
  size: 40Gi
  # storageClass: "-"

service:
  type: ClusterIP
  port:
    name: mapproxy
    port: 8080
    targetPort: nginx
    protocol: TCP

nginx:
  image:
    registry: 643vlk6z.gra7.container-registry.ovh.net/world-cereal
    name: nginx
    tag: latest
    pullPolicy: IfNotPresent
  ports:
    - name: nginx
      containerPort: 80
      protocol: TCP
#   livenessProbe:
#     httpGet:
#       path: /
#       port: http
#     initialDelaySeconds: 20
#     timeoutSeconds: 10
#     periodSeconds: 5
#   readinessProbe:
#     httpGet:
#       path: /
#       port: http
#     initialDelaySeconds: 5
#     timeoutSeconds: 2
#     periodSeconds: 5

mapserver:
  nameOverride: mapserver
  replicaCount: 1
  image:
    registry: 643vlk6z.gra7.container-registry.ovh.net/world-cereal
    name: docker-mapserver
    tag: latest
    pullPolicy: IfNotPresent
  # Override this dummy when installing
  mapfiles:
    # awsCredentials: config/mapfiles/aws_credentials.inc.map.sample
      postgresConnection: config/mapfiles/postgres_connection.inc.map.sample
  ports:
    - name: mapserver
      containerPort: 80
      protocol: TCP
  env:
    - name: "IO_TIMEOUT"
      value: "600"
  service:
    port:
      name: mapserver
      port: 80
      targetPort: mapserver
      protocol: TCP
  nodeSelector:
    role: kong
