
nameOverride: pgsql



pgpool:
  # Create pods on System nodes
  nodeSelector: 
    system-tag: world-cereal-system
  podAntiAffinityPreset: hard
  replicaCount: 3
  existingSecret: pgsqlha-pgpool
  connectionLifeTime: 120

postgresql:
  existingSecret: system-db
  username: postgres
  initdbScripts:
    db.sql: |
      CREATE DATABASE kong OWNER postgres;
      CREATE DATABASE bn_keycloak OWNER postgres;
      CREATE DATABASE grafana OWNER postgres;
  # Create pods on System nodes
  nodeSelector: 
    system-tag: world-cereal-system
  podAntiAffinityPreset: hard
  replicaCount: 3
  # maxConnections: 512

  # => UNTESTED
  extendedConf: |
    max_connections = 512
    shared_buffers = 80MB

volumePermissions:
  enabled: true

persistence:
  enabled: true


