
# nameOverride: pgsql

pgpool:
  # Create pods on System nodes
  nodeSelector: 
    system-tag: world-cereal-system

postgresql:
  existingSecret: system-db
  username: postgres
  initdbScripts:
    db.sql: |
      CREATE DATABASE kong OWNER postgres;
      CREATE DATABASE bn_keycloak OWNER postgres;

  # Create pods on System nodes
  nodeSelector: 
    system-tag: world-cereal-system

  # Using affinity to schedule one pod per node
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/instance
                operator: In
                values:
                  - pgsqlha
          topologyKey: kubernetes.io/hostname

volumePermissions:
  enabled: true

persistence:
  enabled: true


