apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mapserver.fullname" . }}-secret
type: Opaque
data:
  postgres_connection.inc.map: {{ required "A path to postgres connection file (mapserver.mapfiles.postgresConnection) is required!" .Values.mapserver.mapfiles.postgresConnection | b64enc }}
