apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: keycloak-ingress
  namespace: keycloak
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules: 
    - http:
        paths:
          - path: /auth
            backend:
              serviceName: keycloak
              servicePort: 80   
