apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: keycloak-ingress
  namespace: keycloak
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host : auth.dev.worldcereal.csgroup.space 
      http:
        paths:
          - path: /
            backend:
              serviceName: keycloak # The service name inside the namespace with that will access 
              servicePort: 80   
