# helm install keycloak  bitnami/keycloak --create-namespace --namespace=keycloak -f keycloak-value.yaml
image:
  registry: docker.io
  repository: bitnami/keycloak
  tag: {{charts/keycloak/keycloak}}  
  debug: true

extraEnv:
- name: KEYCLOAK_LOG_LEVEL
  value: DEBUG
- name: WILDFLY_LOG_LEVEL
  value: DEBUG
- name: ROOT_LOG_LEVEL
  value: DEBUG

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/strip-path: "false"
    kubernetes.io/tls-acme: "true"
  hostname: auth.
  path: /
  tls: true

auth:
  createAdminUser: true
  adminUser: admin
  adminPassword: d29ybGRjZXJlYWwyMDIxCg==


extraEnvVars:
  - name: KEYCLOAK_LOG_LEVEL
    value: INFO  

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
    interval: 10s
    scrapeTimeout: 10s
    honorLabels: false
    additionalLabels:
      release: kube-prometheus-stack
    
