#chart version =1.3.8
csi:
  attacher:
    image:
      repository: k8s.gcr.io/sig-storage/csi-attacher
      tag: v3.1.0
  provisioner:
    topology: "true"
    image:
      repository: k8s.gcr.io/sig-storage/csi-provisioner
      tag: v2.1.1
  snapshotter:
    image:
      repository: k8s.gcr.io/sig-storage/csi-snapshotter
      tag: v2.1.3
  resizer:
    image:
      repository: k8s.gcr.io/sig-storage/csi-resizer
      tag: v1.1.0
  livenessprobe:
    image:
      repository: k8s.gcr.io/sig-storage/livenessprobe
      tag: v2.1.0
  nodeDriverRegistrar:
    image:
      repository: k8s.gcr.io/sig-storage/csi-node-driver-registrar
      tag: v1.3.0
  plugin:
    image:
      repository: docker.io/k8scloudprovider/cinder-csi-plugin
      tag: v1.21.0
secret:
  enabled: true
  create: true
  name: cinder-csi-cloud-config
  data:
    cloud-config: |-
      [Global]
      auth-url=https://cf2.cloudferro.com:5000/v3
      username=TOSET
      password=TOSET
      region=TOSET
      domain-name=TOSET
      tenant-id=TOSET
      tenant-name=TOSET

      [BlockStorage]                                         
      bs-version=v3
      ignore-volume-az=False


storageClass:
  enabled: true
  delete:
    isDefault: true
    allowVolumeExpansion: true
  retain:
    isDefault: false
    allowVolumeExpansion: true