
nodeSelector:
  role: kong 

auth:
  enabled: true
  rootUser: root
  username: "graylog"
  database: "graylog"


persistence:
  enabled: true
#  storageClass: "standard"
  accessModes:
    - ReadWriteOnce
  size: 8Gi

