imagePullSecrets:
   - name: aws-registry

tags:
  install-elasticsearch: false
  install-mongodb: false

graylog:

  image:
    repository: "graylog/graylog"
    tag: "4.3.3-1"
  
#  Content packs Config map Mounts
  extraVolumeMounts:
    - name: graylog-contentpacks
      mountPath: /usr/share/graylog/data/content-packs

#  Content packs Config map Mounts
  extraVolumes:
    - name: graylog-contentpacks
      configMap: 
        name: graylog-contentpacks
        
  config: |
    elasticsearch_mute_deprecation_warnings = true
    content_packs_loader_enabled = true
    content_packs_dir = /usr/share/graylog/data/content-packs/
    content_packs_auto_install = contentpacks.json,grok-patterns.json

  env:
    GRAYLOG_TRUSTED_PROXIES: 10.2.0.0/16

  replicas: 2
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name 
            operator: In
            values:
            - graylog
        topologyKey: kubernetes.io/hostname

  persistence:
    enabled: true
    size: "10Gi" 

  nodeSelector:
#    role: kong 
    system-tag: world-cereal-system
  # resources:     
  #   limits:
  #     cpu: 2000m
  #     memory: 4096Mi
  #   requests:
  #     cpu: 500m
  #     memory: 3072Mi

  #heapSize: "4g"

  metrics:
    enabled: true

  rootUsername: "admin"

  mongodb:
    #uri: "mongodb://graylog:PASS@mongo-mongodb-headless.logging.svc.cluster.local/graylog&readPreference=primary"  
    uriSecretName: mongodb-access
    uriSecretKey: uri

  init:
    kubectlVersion: "v1.22.10"

  elasticsearch:
    hosts: "http://elastic-elasticsearch-master.logging.svc.cluster.local:9200" 
    version: 7 

  provisioner:
    enabled: true
    useGraylogServiceAccount: false
    
    nodeSelector:
      system-tag: world-cereal-system

    script: |
      IDS=$(curl -u "admin:$GRAYLOG_PASSWORD_SECRET" -X GET --header 'Content-Type: application/json' --header 'X-Requested-By: localhost' http://graylog-master.logging.svc.cluster.local:9000/api/system/inputs)
      RES=$?
      echo $RES
      if [ $RES -ne 0 ]
      then 
        echo 'Wait for master to be started'
        exit 1
      else
        json_header='{"username_header": "X-Username","enabled": "true"}'
          curl -v -u "admin:$GRAYLOG_PASSWORD_SECRET" -X PUT --header 'Content-Type: application/json' --header 'X-Requested-By: localhost' --data-binary "${json_header}" http://graylog-master.logging.svc.cluster.local:9000/api/system/authentication/http-header-auth-config
        json_user='{"first_name":"Operator","last_name":"Graylog","username":"operator","email":"operator@operator.fr","password":"{{ graylog.operator_password }}","roles":["Admin"], "permissions":[]}'
          curl -v -u "admin:$GRAYLOG_PASSWORD_SECRET" -X POST --header 'Content-Type: application/json' --header 'X-Requested-By: localhost' --data-binary "${json_user}" http://graylog-master.logging.svc.cluster.local:9000/api/users
      fi