apiVersion: apps/v1
kind: Deployment
metadata:
  name: be
  namespace: vdm
  labels:
    app: be
spec:
  #replicas: 3
  selector:
    matchLabels:
      app: be
  template:
    metadata:
      labels:
        app: be
    spec:
      imagePullSecrets:
      - name: harborcs 
      containers:
        - env:
            - name: TZ
              value: Europe/Prague      
          name: be
          image: hfjcmwgl.gra5.container-registry.ovh.net/world-cereal/gisat/be-core:dev
          ports:
            - containerPort: 9850
          volumeMounts:
            - mountPath: "/usr/src/app/config.js"
              name: be-hostpath0
              subPath: "config.js"
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: be-hostpath0
          configMap:
            name: be-hostpath0
      nodeSelector:
        role: kong
---          
apiVersion: v1
kind: Service
metadata:
  name: be
  namespace: vdm
spec:
  selector:
    app: be
  ports:
    - protocol: TCP
      port: 9850
      targetPort: 9850