apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg
  namespace: vdm
  labels:
    app: pg
spec:
  #replicas: 3
  selector:
    matchLabels:
      app: pg
  template:
    metadata:
      labels:
        app: pg
    spec:
      imagePullSecrets:
      - name: harborcs 
      containers:
        - args:
            - postgres
            - -c
            - config_file=/etc/postgresql/postgresql.conf
          env:
            - name: POSTGRES_CONFIG
              value: /etc/postgresql/postgresql.conf
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: TZ
              value: Europe/Prague    
          name: pg
          image: hfjcmwgl.gra5.container-registry.ovh.net/world-cereal/gisat/postgis:13-backup
          ports:
          - containerPort: 5432
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: pg-data
              subPath: postgres
            - mountPath: "/etc/postgresql/postgresql.conf"
              name: pg-hostpath1
              subPath: "postgresql.conf"
              readOnly: true
      volumes:
      - name: pg-data
        persistentVolumeClaim:
          claimName: pg-data
      - name: pg-hostpath1
        configMap:  
          name: pg-hostpath1
---
apiVersion: v1
kind: Service
metadata:
  name: pg
  namespace: vdm
spec:
  selector:
    app: pg
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432