apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pg
  namespace: vdm
  labels:
    app: pg
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: pg
    spec:
      containers:
      - name: pg
        image: gisat/postgis:13-backup
        args:
        - postgres
        - -c
        - config_file=/etc/postgresql/postgresql.conf
        env:
        - name: BACKUP_PATH
          value: /mnt/archive
        - name: POSTGRES_CONFIG
          value: /etc/postgresql/postgresql.conf
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: TZ
          value: Europe/Prague
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pg-data
        - mountPath: /etc/postgresql/postgresql.conf
          name: pg-claim1
          readOnly: true
        - mountPath: /mnt/archive
          name: pg-claim2
      restartPolicy: Always
      imagePullSecrets:
        - name: worldcereal-harbor-secrets 
      volumes:
      - name: pg-data
        persistentVolumeClaim:
          claimName: pg-data
---
apiVersion: v1
kind: Service
metadata:
  name: pg-service
  namespace: vdm
spec:
  selector:
    app: be
  ports:
    - port: 5432
      targetPort: 5432  
  type: ClusterIP          
