apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: vdm
  labels:
    app: redis
spec:
  #replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      imagePullSecrets:
      - name: harborcs 
      containers:
        - env:
            - name: TZ
              value: "Europe/Prague"      
          name: redis
          image: hfjcmwgl.gra5.container-registry.ovh.net/world-cereal/gisat/redis:latest
          ports:
          - containerPort: 6379
      nodeSelector:
        role: kong

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: vdm
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379