apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mapproxy.fullname" . }}-status-page
data:
  worldcereal_status.html: |-
    {{- tpl (.Files.Get "config/worldcereal_status.html" ) . | nindent 4 -}}
