
nodeSelector:
  system-tag: world-cereal-system

# architecture: standalone
architecture: replicaset
replicaCount: 3
podAntiAffinityPreset: hard

auth:
  enabled: true
  # rootUser: root
  usernames:
    - graylog
  databases:
    - graylog
  existingSecret: "mongo-db"

persistence:
  enabled: true
  # storageClass: "standard"
  accessModes:
    - ReadWriteOnce
  size: 8Gi


